---
- name: cart configuration
  hosts: cart 
  become: yes

  tasks:

  - name: disabling nodes default version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling nodejs required version 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs 
      state: present
    
  - name: adding roboshop cart
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
      comment: "roboshop system cart"

  - name: deleting /app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete zip file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: downloading zip file
    ansible.builtin.uri:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  
  - name: installing npm dependencies
    community.general.npm:
      path: /app

  - name: copying cart service
    ansible.builtin.template:
      src: cart.service 
      dest: /etc/systemd/system/cart.service

      
  - name: start cart 
    ansible.builtin.service:
      name: cart  
      state: restarted
      enabled: yes

  