---
- name: frontend service
  hosts: frontend
  become: yes

  tasks:
  
  - name: disabling version for nginx 
    ansible.builtin.command: dnf module disable nginx -y

  - name: enabling version for nginx 1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx 
      state: present


  - name: Remove /usr/share/nginx/html/* 
    ansible.builtin.file:
      path: /usr/share/nginx/html/* 
      state: absent

  - name: creating /usr/share/nginx/html/* directory 
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: present



  - name: downloading zip file
    ansible.builtin.uri:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: remove default nginx
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf

  - name: copy nginx.conf
    ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf



  - name: enabling and starting nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes


    
  
