---
- name: mongodb configuration
  hosts: mongodb
  become: yes

  tasks:
  - name: copying mongo.repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb-org
    ansible.builtin.dnf:
      name: mongodb-org
      state: present

  - name: starting and enabling mongodb-org
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes


  - name: replacing port 
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1 '
      replace: '0.0.0.0 '


  - name: restarting service of mongod
    ansible.builtin.service:
      name: mongod 
      state: restarted

