---
- name: payment service 
  hosts: payment
  become: yes

  tasks:

  - name: install dependencies
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
      - python3 
      - gcc 
      - python3-devel  

  - name: adding roboshop user
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
      comment: "roboshop system user" 

  - name: deleting /app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete zip file
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent
  

  - name: downloading zip file
    ansible.builtin.uri:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip  
      dest: /tmp/payment.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: 
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app 

  - name: Reload systemd daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: starting and enabling 
    ansible.builtin.service:
      name: payment
      state: restarted
      enabled: true


