---
- hosts: all
  become: yes
  connection: local

  vars:
    sg_id: sg-0905f25e83735d3d2
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    instances: 
      - mongodb
      - catalogue
    domain_name: kola88.online


  tasks:
    #------ creating ec2 
    - name: ansible ec2 creation
      amazon.aws.ec2_instance:
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"


      loop: "{{ instances }}"
      register: ec2_output

    # printing output of ec2
    - name: printing output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"

    - name: create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "roboshop-{{ env }}.{{ domain_name }}" # roboshop-dev.daws88s.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
      loop: "{{ ec2_output.results }}"
      # when:  # and
      # - item.item == "frontend"
      # - action == "create"