---
- name: user configuration
  hosts: user 
  become: yes

  tasks:

  - name: disabling nodes default version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling nodejs required version 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs 
      state: present
    
  - name: adding roboshop user 
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
      comment: "roboshop system user"

  - name: deleting /app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete zip file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: downloading zip file
    ansible.builtin.uri:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  
  - name: installing npm dependencies
    community.general.npm:
      path: /app

  - name: copying user service
    ansible.builtin.copy:
      src: user.service 
      dest: /etc/systemd/system/user.service

      
  - name: start user
    ansible.builtin.service:
      name: user 
      state: restarted
      enabled: yes

  